# Generated by Django 3.1 on 2020-12-09 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eshop_product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='اسم رنگ')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد رنگ')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='سایز')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد سایز')),
            ],
            options={
                'verbose_name': 'سایز',
                'verbose_name_plural': 'سایزها',
            },
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='ویژگی')),
                ('image_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='آی\u200cدی تصویر')),
                ('quantity', models.IntegerField(default=1, verbose_name='تعداد')),
                ('price', models.IntegerField(default=0, verbose_name='قیمت')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eshop_variant.color', verbose_name='رنگ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_product.product', verbose_name='محصول')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eshop_variant.size', verbose_name='سایز')),
            ],
            options={
                'verbose_name': 'تنوع',
                'verbose_name_plural': 'تنوع\u200cها',
            },
        ),
    ]
