# Generated by Django 3.1 on 2020-12-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_variant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='status',
            field=models.CharField(choices=[('True', 'فعال'), ('False', 'غیرفعال')], default='True', max_length=50, verbose_name='وضعیت'),
        ),
    ]
