# Generated by Django 3.1 on 2020-12-29 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_variant', '0002_variants_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eshop_variant.color', verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eshop_variant.size', verbose_name='سایز'),
        ),
    ]
