# Generated by Django 3.1 on 2020-12-09 13:07

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import eshop_product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eshop_category', '0001_initial'),
        ('eshop_brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان فارسی')),
                ('title_eng', models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان انگلیسی')),
                ('keyword', models.CharField(max_length=250, verbose_name='کلمه کلیدی')),
                ('variant', models.CharField(choices=[('None', 'هیچ'), ('Size', 'سایز'), ('Color', 'رنگ'), ('Size-Color', 'سایزـ\u200cرنگ')], default='None', max_length=10, verbose_name='تنوع')),
                ('description', models.CharField(max_length=300, verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to=eshop_product.models.upload_image_path, verbose_name='تصویر')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('amount', models.IntegerField(verbose_name='تعداد')),
                ('all_sale', models.IntegerField(default=0, verbose_name='تعداد فروش')),
                ('view_count', models.BigIntegerField(default=0, verbose_name='تعداد بازدیدها')),
                ('details', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='جزئيات محصول')),
                ('analyze', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='نقد و بررسی')),
                ('status', models.CharField(choices=[('True', 'فعال'), ('False', 'غیرفعال')], max_length=50, verbose_name='وضعیت')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='عبارت لینک')),
                ('creat_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاده شده در تاریخ')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده در تاریخ')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eshop_brand.brand', verbose_name='برند')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_category.category', verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
