# Generated by Django 3.1 on 2020-12-09 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import eshop_account.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('national_code', models.CharField(blank=True, default='_', max_length=20, verbose_name='کدملی')),
                ('image', models.ImageField(blank=True, upload_to=eshop_account.models.upload_image_path, verbose_name='تصویر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=60, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('ostan', models.CharField(blank=True, max_length=20, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=20, verbose_name='شهر')),
                ('address', models.CharField(blank=True, max_length=150, verbose_name='آدرس پستی')),
                ('post_code', models.IntegerField(blank=True, null=True, verbose_name='کد پستی')),
                ('selected', models.BooleanField(default=False, verbose_name='آدرس منتخب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آدرس کاربر',
                'verbose_name_plural': 'آدرس کاربران',
            },
        ),
    ]
