# Generated by Django 3.1 on 2020-12-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_account', '0002_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'تاریخ بازدید', 'verbose_name_plural': 'تاریخچه بازدیدها'},
        ),
    ]
