# Generated by Django 3.1 on 2020-12-15 13:13

from django.db import migrations, models
import eshop_account.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_account', '0003_auto_20201209_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=eshop_account.models.upload_image_path, verbose_name='تصویر'),
        ),
    ]
