# Generated by Django 3.1 on 2020-12-29 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('eshop_account', '0004_auto_20201215_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
