# Generated by Django 3.1 on 2020-12-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eshop_product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('status', models.CharField(choices=[('True', 'فعال'), ('False', 'غیرفعال')], default=True, max_length=50, verbose_name='وضعیت')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='عبارت لینک')),
                ('creat_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاده شده در تاریخ')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده در تاریخ')),
                ('product', models.ManyToManyField(blank=True, to='eshop_product.Product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب\u200cها',
            },
        ),
    ]
