# Generated by Django 3.1 on 2020-12-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product', '0003_auto_20201229_0922'),
        ('eshop_tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='eshop_product.Product', verbose_name='محصول'),
        ),
    ]
