# Generated by Django 3.2.25 on 2024-12-19 09:18

from django.db import migrations, models
import eshop_slider.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_slider', '0002_alter_slider_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerLeft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('link', models.URLField(max_length=150, verbose_name='لینک')),
                ('image', models.ImageField(blank=True, null=True, upload_to=eshop_slider.models.upload_image_path, verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'بنر چپ',
                'verbose_name_plural': 'بنر چپ',
            },
        ),
        migrations.CreateModel(
            name='BannerRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('link', models.URLField(max_length=150, verbose_name='لینک')),
                ('image', models.ImageField(blank=True, null=True, upload_to=eshop_slider.models.upload_image_path, verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'بنر راست',
                'verbose_name_plural': 'بنر راست',
            },
        ),
    ]
