# Generated by Django 3.1 on 2020-12-09 12:56

from django.db import migrations, models
import eshop_brand.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='برند')),
                ('title_eng', models.CharField(max_length=150, verbose_name='عنوان انگلیسی')),
                ('keyword', models.CharField(max_length=250, verbose_name='کلمه کلیدی')),
                ('description', models.CharField(max_length=300, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, upload_to=eshop_brand.models.upload_image_path, verbose_name='تصویر')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='عبارت لینک')),
                ('creat_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاده شده در تاریخ')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده در تاریخ')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
            },
        ),
    ]
