# Generated by Django 3.1 on 2020-12-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='نام و نام\u200cخانوادگی')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='ایمیل')),
                ('subject', models.CharField(blank=True, max_length=50, verbose_name='موضوع')),
                ('message', models.TextField(blank=True, max_length=255, verbose_name='پیام')),
                ('status', models.CharField(choices=[('New', 'جدید'), ('Read', 'خوانده شده'), ('Closed', 'بسته')], default='New', max_length=10, verbose_name='وضعیت')),
                ('ip', models.CharField(blank=True, max_length=20, verbose_name='آی\u200cپی')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='یادداشت')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاده شده در')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='آخرین آپدیت')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'پیام\u200c\u200cهای مخاطبین',
            },
        ),
    ]
