# Generated by Django 3.1 on 2020-12-09 14:32

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import eshop_setting.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('keyword', models.CharField(max_length=250, verbose_name='کلمه کلیدی')),
                ('description', models.CharField(max_length=300, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to=eshop_setting.models.upload_image_cat_faq_path, verbose_name='تصویر')),
                ('status', models.CharField(choices=[('True', 'فعال'), ('False', 'غیرفعال')], max_length=50, verbose_name='وضعیت')),
                ('creat_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاده شده در تاریخ')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده در تاریخ')),
            ],
            options={
                'verbose_name': 'دسته سوال',
                'verbose_name_plural': 'دسته\u200cبندی\u200c سوالات',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('keywords', models.CharField(max_length=255, verbose_name='کلمه کلیدی')),
                ('description', models.CharField(max_length=255, verbose_name='توضیحات')),
                ('company', models.CharField(max_length=50, verbose_name='نام شرکت')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='تلفن')),
                ('mobile', models.CharField(blank=True, max_length=50, verbose_name='موبایل')),
                ('fax', models.CharField(blank=True, max_length=15, verbose_name='فکس')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='ایمیل')),
                ('smtpserver', models.CharField(blank=True, max_length=50)),
                ('smtpemail', models.CharField(blank=True, max_length=50)),
                ('smtppassword', models.CharField(blank=True, max_length=10)),
                ('smtpport', models.CharField(blank=True, max_length=5)),
                ('logo', models.ImageField(blank=True, upload_to=eshop_setting.models.upload_image_path, verbose_name='لوگو')),
                ('facebook', models.CharField(blank=True, max_length=50, verbose_name='فیسبوک')),
                ('instagram', models.CharField(blank=True, max_length=50, verbose_name='اینستاگرام')),
                ('twitter', models.CharField(blank=True, max_length=50, verbose_name='توئیتر')),
                ('youtube', models.CharField(blank=True, max_length=50, verbose_name='یوتوب')),
                ('copy_right', models.CharField(max_length=50, verbose_name='کپی رایت')),
                ('aboutus', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='درباره ما')),
                ('contact', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='تماس با ما')),
                ('references', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='رفرنس')),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10, verbose_name='وضعیت')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='آخرین آپدیت')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='سوال')),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='پاسخ')),
                ('status', models.CharField(choices=[('True', 'فعال'), ('False', 'غیرفعال')], default='True', max_length=10, verbose_name='وضعیت')),
                ('mostAsked', models.BooleanField(default=False, verbose_name='آیا سوال پرتکرار است؟')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='آپدیت در')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_setting.faqcategory', verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
            },
        ),
    ]
