# Generated by Django 3.2.25 on 2024-12-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_setting', '0002_auto_20210618_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='domain',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
