# Generated by Django 3.2.25 on 2024-12-17 06:08

from django.db import migrations, models
import eshop_setting.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_setting', '0003_sitesetting_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='enemad',
            field=models.ImageField(blank=True, upload_to=eshop_setting.models.upload_image_path),
        ),
    ]
