# Generated by Django 3.2.25 on 2024-12-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_setting', '0004_sitesetting_enemad'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='enemad_code',
            field=models.TextField(blank=True),
        ),
    ]
