# Generated by Django 3.2.25 on 2024-12-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_setting', '0006_remove_sitesetting_enemad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='facebook',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='telegram',
            field=models.CharField(blank=True, max_length=150, verbose_name='تلگرام'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='instagram',
            field=models.CharField(blank=True, max_length=150, verbose_name='اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='twitter',
            field=models.CharField(blank=True, max_length=150, verbose_name='توئیتر'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='youtube',
            field=models.CharField(blank=True, max_length=150, verbose_name='یوتوب'),
        ),
    ]
