# Generated by Django 3.1 on 2020-12-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='en_title',
            field=models.CharField(default='n', max_length=50, verbose_name='عنوان انگلیسی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True, verbose_name='عبارت لینک'),
        ),
    ]
