# Generated by Django 3.1 on 2020-12-14 08:39

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_category', '0002_auto_20201209_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='eshop_category.category', verbose_name='دسته\u200cمادر'),
        ),
    ]
