# Generated by Django 3.1 on 2020-12-09 13:25

from django.db import migrations, models
import django.db.models.deletion
import eshop_image.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eshop_product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, upload_to=eshop_image.models.upload_image_path, verbose_name='تصویر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
            },
        ),
    ]
