# Generated by Django 3.1 on 2021-02-02 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product', '0003_auto_20201229_0922'),
        ('eshop_image', '0002_auto_20201229_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery', to='eshop_product.product', verbose_name='محصول'),
        ),
    ]
