# Generated by Django 3.1 on 2020-12-09 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eshop_variant', '0001_initial'),
        ('eshop_product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eshop_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=10, verbose_name='کد سفارش')),
                ('pay_way', models.CharField(choices=[('online', 'پرداخت آنلاین'), ('creditCard', 'کیف پول اعتباری')], default='online', max_length=50, verbose_name='نحوه پرداخت')),
                ('total', models.IntegerField(verbose_name='جمع مبلغ کل سفارشات')),
                ('amount', models.IntegerField(verbose_name='جمع تعداد کل سفارشات')),
                ('status', models.CharField(choices=[('New', 'جدید'), ('Accepted', 'تایید سفارش'), ('Preparing', 'آماده سازی سفارش'), ('OutCompany', 'خروج از مرکز پردازش'), ('InPostOffice', 'تحویل به پست'), ('OnShipping', 'مرکز مبادلات پست'), ('Arrive', 'تحویل به مشتری'), ('Canceled', 'لغو شده')], default='New', max_length=30, verbose_name='وضعیت')),
                ('ip', models.CharField(blank=True, max_length=20, verbose_name='آی\u200cپی')),
                ('admin_note', models.CharField(blank=True, max_length=100, verbose_name='یادداشت ادمین')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='آخرین آپدیت')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eshop_account.useraddress', verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='PostWay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('way', models.CharField(max_length=60, verbose_name='روش سفارش')),
                ('price', models.IntegerField(verbose_name='هزینه ارسال')),
                ('selected', models.BooleanField(default=False, verbose_name='روش پست منتخب')),
            ],
            options={
                'verbose_name': 'روش\u200c\u200c ارسال',
                'verbose_name_plural': 'روش\u200cهای ارسال',
            },
        ),
        migrations.CreateModel(
            name='ShopCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eshop_product.product', verbose_name='محصول')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eshop_variant.variants', verbose_name='مدل محصول')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبدهای خرید',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('amount', models.IntegerField(verbose_name='قیمت کل')),
                ('status', models.CharField(choices=[('New', 'جدید'), ('Accepted', 'تایید سفارش'), ('Canceled', 'کنسل سفارش')], default='New', max_length=30, verbose_name='وضعیت')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='آخرین آپدیت')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_order.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_product.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eshop_variant.variants', verbose_name='مدل محصول')),
            ],
            options={
                'verbose_name': 'سفارش محصول',
                'verbose_name_plural': 'سفارشات محصولات',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='post_way',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eshop_order.postway', verbose_name='نحوه ارسال'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
