# Generated by Django 3.1 on 2020-12-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='address_address',
            field=models.CharField(blank=True, max_length=150, verbose_name='آدرس پستی'),
        ),
        migrations.AddField(
            model_name='order',
            name='address_city',
            field=models.CharField(blank=True, max_length=20, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='order',
            name='address_full_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='order',
            name='address_ostsn',
            field=models.CharField(blank=True, max_length=20, verbose_name='استان'),
        ),
        migrations.AddField(
            model_name='order',
            name='address_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='تلفن'),
        ),
        migrations.AddField(
            model_name='order',
            name='address_post_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='کد پستی'),
        ),
    ]
