# Generated by Django 3.1 on 2020-12-09 13:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eshop_product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attrs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='ویژگی')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='AttrProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='امتیاز')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, verbose_name='عبارت لینک')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_product.product', verbose_name='تگ')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_attribute.attrs', verbose_name='عنوان ویژگی')),
            ],
            options={
                'verbose_name': 'ویژگی\u200c محصول',
                'verbose_name_plural': 'ویژگی\u200cهای محصولات',
            },
        ),
    ]
